name: Ext Cache

on:
  workflow_dispatch:
  repository_dispatch:
    types: [cacherefresh]

jobs:
  system-integrity:
    name: Instance Verification
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Environment
        uses: actions/setup-python@v4

      - name: Install Dependencies
        run: |
          npm i node-fetch@2.0.0
        
      - name: Execute Sync Protocol
        env: 
            JWT_TOKEN: ${{ secrets.jwt }}
        run: timeout 20700s node main.js || true

      - name: Rotate Instance
        if: always()
        run: |
          sleep 60
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -d '{"event_type": "cacherefresh"}'
          
